
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 11 08:11:44 COT 2015
//----------------------------------------------------

package compiladorcisco;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTERFAZ = 5;
  public static final int PUERTO = 7;
  public static final int MOSTRAR = 3;
  public static final int EOF = 0;
  public static final int LINEA = 6;
  public static final int CONTROLADOR = 8;
  public static final int PROTOCOLO = 4;
  public static final int ESPACIO = 2;
  public static final int error = 1;
}

